# Generated by Django 2.2.8 on 2019-12-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=300)),
                ('BOLZ', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('jednostka', models.CharField(blank=True, max_length=10)),
                ('seria', models.CharField(blank=True, max_length=50)),
                ('data_waznosci', models.DateField(blank=True, null=True)),
                ('cena_netto', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cena_brutto', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('PKWiU', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
