# Generated by Django 2.2.8 on 2019-12-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lek',
            name='id_towaru',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lek',
            name='kod_kresowy',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lek',
            name='BOLZ',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
