# Generated by Django 2.2.8 on 2019-12-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191202_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_faktury', models.BigIntegerField(blank=True, null=True)),
                ('data_wystawienia', models.DateField(blank=True, null=True)),
                ('data_sprzedazy', models.DateField(blank=True, null=True)),
                ('termin_platnosci', models.DateField(blank=True, null=True)),
                ('id_sprzedawcy', models.PositiveIntegerField(blank=True, null=True)),
                ('korekta', models.BooleanField()),
                ('wartosc_netto', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wartosc_brutto', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
