# Generated by Django 2.2.8 on 2019-12-02 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_faktura'),
    ]

    operations = [
        migrations.AddField(
            model_name='lek',
            name='faktura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Faktura'),
        ),
    ]
