# Generated by Django 3.0 on 2019-12-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191207_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lek',
            old_name='kod_kresowy',
            new_name='kod_kreskowy',
        ),
    ]
