# Generated by Django 2.2 on 2019-12-18 12:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191207_1224'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lek',
            managers=[
                ('all', django.db.models.manager.Manager()),
            ],
        ),
    ]
