# Generated by Django 2.2 on 2020-01-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191218_1301'),
        ('app', '0010_lek_data_wydania'),
    ]

    operations = [
    ]
